# Generated by Django 3.1.7 on 2021-04-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0002_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запретить комментирование'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Редактировано')),
                ('tag', models.SlugField(verbose_name='Тег')),
                ('object_id', models.PositiveIntegerField(verbose_name='Уникальный номер')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Контент')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
